### ISSUE TITLE
Set Max Window Size

### ISSUE THREAD

**Issue by JimWallace** [L1MeN9Yu/Elva#5]
I've run across some files I'd like to work with where it's required to set the Max Window Size. I've been able to work with them by creating my own version of the `decompress(reader:writer:config:)` method, which includes this call:

`ZSTD_DCtx_setParameter(decompressContext, ZSTD_d_windowLogMax, 31)`

I'm wondering if there's an elegant way to wrap this into the `DecompressConfig` option, and then pass that to `createContext()`?  Or should it be set outside of the `createContext()` function? 

Is this something worth submitting a PR over?

**Comment by L1MeN9Yu** [comment]
added in #6 

create a `DecompressConfig` instance like this : `DecompressConfig(parameters: [.windowLogMax(31)])`

**Comment by JimWallace** [comment]
Thanks for such a speedy response! I've updated and tested code on my end and can confirm it works as expected.
